### ISSUE TITLE
Translation don't work

### ISSUE THREAD

**Issue by eson57** [ojhaapala/wht#29]
...or where do I change it? Swedish .qt file is present, but it don't translate.

SFOS v1.1.4
WHT v1.0.4

**Comment by ojhaapala** [comment]
Oh my bad. I forgot to include swedish translation to the update (that's in QA at the moment). I'll have to include it next time. Sorry.

https://www.transifex.com/projects/p/working-hours-tracker/

**Comment by eson57** [comment]
Ok, I see. 
Is there a reason for not implementing general language support? Because that way, new translators could test there translations by adding there own .qm file.

**Comment by ojhaapala** [comment]
Hmm. How would that work?
I don't know what general language support means.

**Comment by eson57** [comment]
Well, I'm not a programmer so I can't give instructions, but I've translated several apps where I can just put my qm file in the app translation folder, and it will work out of the box.
[ContactInfo](https://github.com/Logic-gate/ContactInfo) is one of my latest translations where it worked, if that would be helpful.

**Comment by ojhaapala** [comment]
Ok

**Comment by eson57** [comment]
Still no Swedish translation in v. 1.0.6 ?

**Comment by ojhaapala** [comment]
Included Swedish translation into 1.0.7. Now in openrepos

**Comment by eson57** [comment]
Thanks
