### ISSUE TITLE
Removing multiple hours-items during remorse timer can fail index being wrong

### ISSUE THREAD

**Issue by tigeli** [ojhaapala/wht#3]
If you try to remove multiple hour-items so that remorse timer is still running for the first item.. the removal might fail as the index is not anymore correct (or incorrect hour-item is removed eg. topmost item is set to be removed, while remorse timer is running remove the item below and you will get your item below the second removal deleted).

8<- first remove this
7<-while remorse timer running remove this
6

You will end up with

7

as the 6 has index which 7 had first.

**Comment by ojhaapala** [comment]
Could probably be fixed by deleting by the unique id not the index.

**Comment by ojhaapala** [comment]
Seems to delete correctly from the database though.
