### ISSUE TITLE
Bug: Time counter on cover does not get updated after the phone awakes from sleeping

### ISSUE THREAD

**Issue by jobe-m** [ojhaapala/wht#9]
I usually start the timer in the morning when I come to work. The app is then just running in background with visible cover.
Now when I wake up the phone after a couple of time to see how much time I already spend at work the time counter (hour, minute) on the cover shows the last time before the phone went into sleeping mode. Thus I need to wait for appr. one minute until the cover timer gets updated.
EDIT: The bug also appears inside the app. The timer also shows the old time until it gets updated by the timer object within the next minute.

I know this is a design limitation in timer handling on Sailfhish OS. I had it also with my app Time2Go. A workaround would be to update the cover timer every second. Or maybe you discover a way to get notified when the phone comes out from deep sleep mode...

Nice work so far! Keep it up!

**Comment by ojhaapala** [comment]
Yes this is a known bug. I'm trying to not waste battery but definitely have to find a way to update the cover when needed.
